### ISSUE TITLE
LiveTV Regressions in beta11 release

### ISSUE THREAD

**Issue by doodlebro** [Andy2244/jellyfin-androidtv-zidoo#3]
### Describe the bug

After updating to beta 11, LiveTV channels and the TV guide itself crash the app. I am using an HDHomerun with SchedulesDirect as a data source. After reverting to beta10, LiveTV and the TV guide do not cause crashes as soon as a channel is started, or a second after the TV guide is opened. The crash logs for each case look similar, so I am only including one log. I do not believe there is an associated ffmpeg log. Let me know if I can provide more information.

### Logs

---
client: Jellyfin for Android TV
client_version: 0.14.9-zidoo_edition.beta11
client_repository: https://github.com/Andy2244/jellyfin-androidtv-zidoo
type: crash_report
format: markdown
---
### Logs

***Stack Trace***: 
```log
java.lang.IllegalArgumentException: Cannot format given Object as a Date
	at java.text.DateFormat.format(DateFormat.java:306)
	at java.text.Format.format(Format.java:157)
	at org.jellyfin.androidtv.util.apiclient.BaseItemUtils.getProgramSubText(BaseItemUtils.kt:145)
	at org.jellyfin.androidtv.ui.InfoRowView.addProgramInfo(InfoRowView.kt:238)
	at org.jellyfin.androidtv.ui.InfoRowView.buildDefaultInfoRow(InfoRowView.kt:155)
	at org.jellyfin.androidtv.ui.InfoRowView.updateView(InfoRowView.kt:129)
	at org.jellyfin.androidtv.ui.InfoRowView.access$updateView(InfoRowView.kt:43)
	at org.jellyfin.androidtv.ui.InfoRowView$setBaseItem$$inlined$doOnPreDraw$1.run(View.kt:433)
	at androidx.core.view.OneShotPreDrawListener.onPreDraw(OneShotPreDrawListener.java:71)
	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:977)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2476)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1462)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7185)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:696)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```  
***Logcat***: 
```log
--------- beginning of main
11-20 10:49:50.983 D/SessionRepositoryImpl(13679): Updating current session. userId=e84c349c-8693-48a1-bbfe-c75f859cd50d apiBindingSuccess=true
11-20 10:49:50.983 I/org.jellyfin.sdk.api.client.KtorClient(13679): GET http://URL:8096/Users/Me
11-20 10:49:51.017 I/org.jellyfin.sdk.api.client.KtorClient(13679): GET http://URL:8096/DisplayPreferences/livetv?userId=e84c349c-8693-48a1-bbfe-c75f859cd50d&client=jellyfin-androidtv
11-20 10:49:51.033 I/org.jellyfin.sdk.api.client.KtorClient(13679): GET http://URL:8096/DisplayPreferences/usersettings?userId=e84c349c-8693-48a1-bbfe-c75f859cd50d&client=emby
11-20 10:49:51.044 I/StartupActivity$onPermissionsGranted(13679): Found a session in the session repository, waiting for the currentUser in the application class.
11-20 10:49:51.045 I/StartupActivity$onPermissionsGranted(13679): CurrentUser changed to e84c349c-8693-48a1-bbfe-c75f859cd50d while waiting for startup.
11-20 10:49:51.046 D/StartupActivity(13679): Determining next activity (action=android.intent.action.MAIN, itemId=null, itemIsUserView=false)
11-20 10:49:51.048 D/SessionRepositoryImpl(13679): Restoring session
11-20 10:49:51.054 I/org.jellyfin.sdk.api.client.KtorClient(13679): GET http://URL:8096/Playback/BitrateTest?size=4000000
11-20 10:49:51.056 D/org.jellyfin.sdk.api.sockets.SocketInstance(13679): Reconnect requested
11-20 10:49:51.056 I/org.jellyfin.sdk.api.sockets.SocketInstance(13679): Reconnecting
11-20 10:49:51.057 D/org.jellyfin.sdk.api.sockets.helper.ReconnectHelper(13679): Notified about reconnect, attempts=1
11-20 10:49:51.058 D/org.jellyfin.sdk.api.sockets.SocketInstance(13679): Reconnect requested
11-20 10:49:51.058 I/chatty  (13679): uid=10051(org.jellyfin.androidtv) DefaultDispatch identical 1 line
11-20 10:49:51.058 D/org.jellyfin.sdk.api.sockets.SocketInstance(13679): Reconnect requested
11-20 10:49:51.058 D/org.jellyfin.sdk.api.sockets.SocketInstance(13679): Reconnect requested
11-20 10:49:51.060 I/org.jellyfin.sdk.api.client.KtorClient(13679): POST http://URL:8096/Sessions/Capabilities?playableMediaTypes=Video%2CAudio&supportedCommands=DisplayMessage%2CSendString&supportsMediaControl=true&supportsSync=false&supportsPersistentIdentifier=true
11-20 10:49:51.075 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(13679): WebSocket has opened
11-20 10:49:51.076 D/org.jellyfin.sdk.api.sockets.helper.ReconnectHelper(13679): Notified about connect, attempts reset
11-20 10:49:51.097 D/org.jellyfin.sdk.api.sockets.SocketInstance(13679): Credential update requested
11-20 10:49:51.098 D/org.jellyfin.sdk.api.sockets.SocketInstance(13679): Unable to update credentials: credentials did not change
11-20 10:49:51.128 D/StartupActivity(13679): Opening next activity Intent { flg=0x10004000 cmp=org.jellyfin.androidtv/.ui.browsing.MainActivity }
11-20 10:49:51.144 D/ACRA    (13679): onActivityPaused class org.jellyfin.androidtv.ui.startup.StartupActivity
11-20 10:49:51.153 W/ActivityThread(13679): handleWindowVisibility: no activity for token android.os.BinderProxy@f9e7b55
11-20 10:49:51.159 D/ACRA    (13679): onActivityCreated class org.jellyfin.androidtv.ui.browsing.MainActivity
11-20 10:49:51.159 I/AppThemeCallbacks(13679): Applying theme: DARK
11-20 10:49:51.176 I/BackgroundService(13679): Adding BackgroundServiceFragment to activity
11-20 10:49:51.179 D/ACRA    (13679): onActivityStarted class org.jellyfin.androidtv.ui.browsing.MainActivity
11-20 10:49:51.205 I/lyfin.androidt(13679): Background concurrent copying GC freed 60759(3MB) AllocSpace objects, 23(1052KB) LOS objects, 50% free, 3MB/6MB, paused 255us total 100.844ms
11-20 10:49:51.222 I/BackgroundService(13679): Adding BackgroundServiceFragment to activity
11-20 10:49:51.223 D/MediaManager(13679): Added event listener.  Total listeners: 1
11-20 10:49:51.223 D/jellyfin-apiclient(13679): Adding request to queue: http://URL:8096/LiveTv/Programs/Recommended?UserId=e84c349c-8693-48a1-bbfe-c75f859cd50d&EnableTotalRecordCount=false&IsAiring=true&Limit=1&ImageTypeLimit=1&format=json
11-20 10:49:51.230 D/ACRA    (13679): onActivityResumed class org.jellyfin.androidtv.ui.browsing.MainActivity
11-20 10:49:51.232 I/HomeFragment(13679): Updating audio queue in HomeFragment (onResume)
11-20 10:49:51.233 D/BackgroundServiceFragment(13679): Restoring background drawable
11-20 10:49:51.233 D/BackgroundServiceFragment(13679): Restoring background drawable
11-20 10:49:51.240 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(13679): Receiving (raw) message {"MessageType":"ForceKeepAlive","MessageId":"00000000000000000000000000000000","Data":60}
11-20 10:49:51.244 I/WM-WorkerWrapper(13679): Worker result FAILURE for Work [ id=8842ddf2-7ecb-41be-a607-1ff46f3eb3fe, tags={ org.jellyfin.androidtv.integration.LeanbackChannelWorker } ]
11-20 10:49:51.246 I/org.jellyfin.sdk.api.sockets.helper.KeepAliveHelper(13679): Using a KeepAlive message delay of 30 seconds
11-20 10:49:51.246 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(13679): Sending (raw) message {"MessageType":"KeepAlive","Data":{}}
11-20 10:49:51.249 D/MediaManager(13679): Added event listener.  Total listeners: 2
11-20 10:49:51.251 I/org.jellyfin.sdk.api.sockets.OkHttpWebsocketSession(13679): Receiving (raw) message {"MessageType":"KeepAlive","MessageId":"53cb77079e9444e6a059adceeeff53a0"}
11-20 10:49:51.284 D/mali_winsys(13679): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
11-20 10:49:51.285 I/jellyfin-apiclient(13679): Response received from: http://URL:8096/LiveTv/Programs/Recommended?UserId=e84c349c-8693-48a1-bbfe-c75f859cd50d&EnableTotalRecordCount=false&IsAiring=true&Limit=1&ImageTypeLimit=1&format=json
11-20 10:49:51.309 D/jellyfin-apiclient(13679): Adding request to queue: http://URL:8096/Users/e84c349c-8693-48a1-bbfe-c75f859cd50d/Views?format=json
11-20 10:49:51.358 I/jellyfin-apiclient(13679): Response received from: http://URL:8096/Users/e84c349c-8693-48a1-bbfe-c75f859cd50d/Views?format=json
11-20 10:49:51.377 D/ACRA    (13679): onActivityStopped class org.jellyfin.androidtv.ui.startup.StartupActivity
11-20 10:49:51.378 D/ACRA    (13679): onActivityDestroyed class org.jellyfin.androidtv.ui.startup.StartupActivity
11-20 10:49:51.389 W/libEGL  (13679): EGLNativeWindowType 0xa289f808 disconnect failed
11-20 10:49:51.396 D/jellyfin-apiclient(13679): Adding request to queue: http://URL:8096/LiveTv/Programs/Recommended?Fields=Overview%2CPrimaryImageAspectRatio%2CChannelInfo%2CChildCount&UserId=e84c349c-8693-48a1-bbfe-c75f859cd50d&EnableTotalRecordCount=false&IsAiring=true&Limit=20&ImageTypeLimit=1&format=json
11-20 10:49:51.398 D/jellyfin-apiclient(13679): Adding request to queue: http://URL:8096/Users/e84c349c-8693-48a1-bbfe-c75f859cd50d/Views?format=json
11-20 10:49:51.402 D/jellyfin-apiclient(13679): Adding request to queue: http://URL:8096/Users/e84c349c-8693-48a1-bbfe-c75f859cd50d/Items?SortBy=DatePlayed&EnableTotalRecordCount=false&ExcludeLocationTypes=Virtual&MediaTypes=Video&ImageTypeLimit=1&recursive=true&Filters=IsResumable&Fields=PrimaryImageAspectRatio%2COverview%2CItemCounts%2CDisplayPreferencesId%2CChildCount&sortOrder=Descending&Limit=50&format=json
11-20 10:49:51.403 D/jellyfin-apiclient(13679): Adding request to queue: http://URL:8096/Shows/NextUp?Fields=PrimaryImageAspectRatio%2COverview%2CChildCount&UserId=e84c349c-8693-48a1-bbfe-c75f859cd50d&Limit=50&ImageTypeLimit=1&format=json
11-20 10:49:51.406 D/jellyfin-apiclient(13679): Adding request to queue: http://URL:8096/Users/e84c349c-8693-48a1-bbfe-c75f859cd50d/Items/Latest?ParentId=a656b907eb3a73532e40e44b968d0225&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount%2CDateLastMediaAdded%2CDateCreated&IncludeItemTypes=Episode%2CMovie%2CMusicAlbum%2CAudioBook&Limit=50&GroupItems=true&format=json
11-20 10:49:51.407 D/jellyfin-apiclient(13679): Adding request to queue: http://URL:8096/Users/e84c349c-8693-48a1-bbfe-c75f859cd50d/Items/Latest?ParentId=f137a2dd21bbc1b99aa5c0f6bf02a805&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount%2CDateLastMediaAdded%2CDateCreated&IncludeItemTypes=Episode%2CMovie%2CMusicAlbum%2CAudioBook&Limit=50&GroupItems=true&format=json
11-20 10:49:51.408 D/jellyfin-apiclient(13679): Adding request to queue: http://URL:8096/Users/e84c349c-8693-48a1-bbfe-c75f859cd50d/Items/Latest?ParentId=ef1a83be1963fd6974bc6e5901eb87c5&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount%2CDateLastMediaAdded%2CDateCreated&IncludeItemTypes=Episode%2CMovie%2CMusicAlbum%2CAudioBook&Limit=50&GroupItems=true&format=json
11-20 10:49:51.410 D/jellyfin-apiclient(13679): Adding request to queue: http://URL:8096/Users/e84c349c-8693-48a1-bbfe-c75f859cd50d/Items/Latest?ParentId=63e31d811dd150914d17126747e936aa&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount%2CDateLastMediaAdded%2CDateCreated&IncludeItemTypes=Episode%2CMovie%2CMusicAlbum%2CAudioBook&Limit=50&GroupItems=true&format=json
11-20 10:49:51.416 D/jellyfin-apiclient(13679): Adding request to queue: http://URL:8096/Users/e84c349c-8693-48a1-bbfe-c75f859cd50d/Items/Latest?ParentId=89613829c7faa2d339bac9cccce02855&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount%2CDateLastMediaAdded%2CDateCreated&IncludeItemTypes=Episode%2CMovie%2CMusicAlbum%2CAudioBook&Limit=50&GroupItems=true&format=json
11-20 10:49:51.417 D/jellyfin-apiclient(13679): Adding request to queue: http://URL:8096/Users/e84c349c-8693-48a1-bbfe-c75f859cd50d/Items/Latest?ParentId=3774c44459f387f1acd6b5b5e2f98a2a&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount%2CDateLastMediaAdded%2CDateCreated&IncludeItemTypes=Episode%2CMovie%2CMusicAlbum%2CAudioBook&Limit=50&GroupItems=true&format=json
11-20 10:49:51.419 D/jellyfin-apiclient(13679): Adding request to queue: http://URL:8096/Users/e84c349c-8693-48a1-bbfe-c75f859cd50d/Items/Latest?ParentId=e59b37148e0ff06f0d35b0c3c714e75c&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount%2CDateLastMediaAdded%2CDateCreated&IncludeItemTypes=Episode%2CMovie%2CMusicAlbum%2CAudioBook&Limit=50&GroupItems=true&format=json
11-20 10:49:51.420 I/jellyfin-apiclient(13679): Response received from: http://URL:8096/LiveTv/Programs/Recommended?Fields=Overview%2CPrimaryImageAspectRatio%2CChannelInfo%2CChildCount&UserId=e84c349c-8693-48a1-bbfe-c75f859cd50d&EnableTotalRecordCount=false&IsAiring=true&Limit=20&ImageTypeLimit=1&format=json
11-20 10:49:51.651 I/lyfin.androidt(13679): Background concurrent copying GC freed 30203(1786KB) AllocSpace objects, 6(204KB) LOS objects, 50% free, 4MB/9MB, paused 189us total 102.430ms
11-20 10:49:51.697 D/CardPresenter(13679): Could not get valid blurHash from <http://URL:8096/Items/44ad7cca-4d35-98cf-e4c2-6892f62be015/Images/Primary?maxHeight=540&quality=90&tag=543b6ca4c9f21c87d81daf7a932499c0>
11-20 10:49:51.795 I/jellyfin-apiclient(13679): Response received from: http://URL:8096/Users/e84c349c-8693-48a1-bbfe-c75f859cd50d/Views?format=json
11-20 10:49:51.913 I/.androidtv:acr(13628): Waiting for a blocking GC ProfileSaver
11-20 10:49:51.982 I/lyfin.androidt(13679): Background concurrent copying GC freed 34414(3MB) AllocSpace objects, 2(36KB) LOS objects, 50% free, 18MB/36MB, paused 200us total 168.876ms
11-20 10:49:52.093 I/jellyfin-apiclient(13679): Response received from: http://URL:8096/Users/e84c349c-8693-48a1-bbfe-c75f859cd50d/Items?SortBy=DatePlayed&EnableTotalRecordCount=false&ExcludeLocationTypes=Virtual&MediaTypes=Video&ImageTypeLimit=1&recursive=true&Filters=IsResumable&Fields=PrimaryImageAspectRatio%2COverview%2CItemCounts%2CDisplayPreferencesId%2CChildCount&sortOrder=Descending&Limit=50&format=json
11-20 10:49:52.100 I/jellyfin-apiclient(13679): Response received from: http://URL:8096/Users/e84c349c-8693-48a1-bbfe-c75f859cd50d/Items/Latest?ParentId=ef1a83be1963fd6974bc6e5901eb87c5&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount%2CDateLastMediaAdded%2CDateCreated&IncludeItemTypes=Episode%2CMovie%2CMusicAlbum%2CAudioBook&Limit=50&GroupItems=true&format=json
11-20 10:49:52.100 I/jellyfin-apiclient(13679): Response received from: http://URL:8096/Users/e84c349c-8693-48a1-bbfe-c75f859cd50d/Items/Latest?ParentId=63e31d811dd150914d17126747e936aa&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount%2CDateLastMediaAdded%2CDateCreated&IncludeItemTypes=Episode%2CMovie%2CMusicAlbum%2CAudioBook&Limit=50&GroupItems=true&format=json
11-20 10:49:52.100 I/jellyfin-apiclient(13679): Response received from: http://URL:8096/Users/e84c349c-8693-48a1-bbfe-c75f859cd50d/Items/Latest?ParentId=a656b907eb3a73532e40e44b968d0225&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount%2CDateLastMediaAdded%2CDateCreated&IncludeItemTypes=Episode%2CMovie%2CMusicAlbum%2CAudioBook&Limit=50&GroupItems=true&format=json
11-20 10:49:52.103 I/jellyfin-apiclient(13679): Response received from: http://URL:8096/Users/e84c349c-8693-48a1-bbfe-c75f859cd50d/Items/Latest?ParentId=f137a2dd21bbc1b99aa5c0f6bf02a805&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount%2CDateLastMediaAdded%2CDateCreated&IncludeItemTypes=Episode%2CMovie%2CMusicAlbum%2CAudioBook&Limit=50&GroupItems=true&format=json
11-20 10:49:52.120 I/jellyfin-apiclient(13679): Response received from: http://URL:8096/Users/e84c349c-8693-48a1-bbfe-c75f859cd50d/Items/Latest?ParentId=89613829c7faa2d339bac9cccce02855&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount%2CDateLastMediaAdded%2CDateCreated&IncludeItemTypes=Episode%2CMovie%2CMusicAlbum%2CAudioBook&Limit=50&GroupItems=true&format=json
11-20 10:49:52.136 I/jellyfin-apiclient(13679): Response received from: http://URL:8096/Users/e84c349c-8693-48a1-bbfe-c75f859cd50d/Items/Latest?ParentId=3774c44459f387f1acd6b5b5e2f98a2a&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount%2CDateLastMediaAdded%2CDateCreated&IncludeItemTypes=Episode%2CMovie%2CMusicAlbum%2CAudioBook&Limit=50&GroupItems=true&format=json
11-20 10:49:52.150 I/jellyfin-apiclient(13679): Response received from: http://URL:8096/Users/e84c349c-8693-48a1-bbfe-c75f859cd50d/Items/Latest?ParentId=e59b37148e0ff06f0d35b0c3c714e75c&Fields=PrimaryImageAspectRatio%2COverview%2CChildCount%2CDateLastMediaAdded%2CDateCreated&IncludeItemTypes=Episode%2CMovie%2CMusicAlbum%2CAudioBook&Limit=50&GroupItems=true&format=json
11-20 10:49:52.160 I/jellyfin-apiclient(13679): Response received from: http://URL:8096/Shows/NextUp?Fields=PrimaryImageAspectRatio%2COverview%2CChildCount&UserId=e84c349c-8693-48a1-bbfe-c75f859cd50d&Limit=50&ImageTypeLimit=1&format=json
11-20 10:49:52.977 I/AutoBitrate(13679): Auto bitrate set to: 16640665
11-20 10:49:53.175 I/lyfin.androidt(13679): Background concurrent copying GC freed 183198(15MB) AllocSpace objects, 32(1904KB) LOS objects, 49% free, 19MB/38MB, paused 178us total 229.950ms
11-20 10:49:55.306 D/ACRA    (13679): onActivityPaused class org.jellyfin.androidtv.ui.browsing.MainActivity
11-20 10:49:55.313 W/ActivityThread(13679): handleWindowVisibility: no activity for token android.os.BinderProxy@ce44b13
11-20 10:49:55.322 D/ACRA    (13679): onActivityCreated class org.jellyfin.androidtv.ui.itemdetail.FullDetailsActivity
11-20 10:49:55.323 I/AppThemeCallbacks(13679): Applying theme: DARK
11-20 10:49:55.335 I/BackgroundService(13679): Adding BackgroundServiceFragment to activity
11-20 10:49:55.419 D/jellyfin-apiclient(13679): Adding request to queue: http://URL:8096/Users/e84c349c-8693-48a1-bbfe-c75f859cd50d/Items/edcb0333bfc56de72f65740762c6ce56?format=json
11-20 10:49:55.422 D/ACRA    (13679): onActivityStarted class org.jellyfin.androidtv.ui.itemdetail.FullDetailsActivity
11-20 10:49:55.426 D/ACRA    (13679): onActivityResumed class org.jellyfin.androidtv.ui.itemdetail.FullDetailsActivity
11-20 10:49:55.427 D/BackgroundServiceFragment(13679): Restoring background drawable
11-20 10:49:55.436 I/jellyfin-apiclient(13679): Response received from: http://URL:8096/Users/e84c349c-8693-48a1-bbfe-c75f859cd50d/Items/edcb0333bfc56de72f65740762c6ce56?format=json
11-20 10:49:55.472 D/FullDetailsActivity(13679): Item type: Program
11-20 10:49:55.494 D/mali_winsys(13679): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
11-20 10:49:55.577 D/AndroidRuntime(13679): Shutting down VM
--------- beginning of crash
11-20 10:49:55.578 E/AndroidRuntime(13679): FATAL EXCEPTION: main
11-20 10:49:55.578 E/AndroidRuntime(13679): Process: org.jellyfin.androidtv, PID: 13679
11-20 10:49:55.578 E/AndroidRuntime(13679): java.lang.IllegalArgumentException: Cannot format given Object as a Date
11-20 10:49:55.578 E/AndroidRuntime(13679): 	at java.text.DateFormat.format(DateFormat.java:306)
11-20 10:49:55.578 E/AndroidRuntime(13679): 	at java.text.Format.format(Format.java:157)
11-20 10:49:55.578 E/AndroidRuntime(13679): 	at org.jellyfin.androidtv.util.apiclient.BaseItemUtils.getProgramSubText(BaseItemUtils.kt:145)
11-20 10:49:55.578 E/AndroidRuntime(13679): 	at org.jellyfin.androidtv.ui.InfoRowView.addProgramInfo(InfoRowView.kt:238)
11-20 10:49:55.578 E/AndroidRuntime(13679): 	at org.jellyfin.androidtv.ui.InfoRowView.buildDefaultInfoRow(InfoRowView.kt:155)
11-20 10:49:55.578 E/AndroidRuntime(13679): 	at org.jellyfin.androidtv.ui.InfoRowView.updateView(InfoRowView.kt:129)
11-20 10:49:55.578 E/AndroidRuntime(13679): 	at org.jellyfin.androidtv.ui.InfoRowView.access$updateView(InfoRowView.kt:43)
11-20 10:49:55.578 E/AndroidRuntime(13679): 	at org.jellyfin.androidtv.ui.InfoRowView$setBaseItem$$inlined$doOnPreDraw$1.run(View.kt:433)
11-20 10:49:55.578 E/AndroidRuntime(13679): 	at androidx.core.view.OneShotPreDrawListener.onPreDraw(OneShotPreDrawListener.java:71)
11-20 10:49:55.578 E/AndroidRuntime(13679): 	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:977)
11-20 10:49:55.578 E/AndroidRuntime(13679): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2476)
11-20 10:49:55.578 E/AndroidRuntime(13679): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1462)
11-20 10:49:55.578 E/AndroidRuntime(13679): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7185)
11-20 10:49:55.578 E/AndroidRuntime(13679): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
11-20 10:49:55.578 E/AndroidRuntime(13679): 	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
11-20 10:49:55.578 E/AndroidRuntime(13679): 	at android.view.Choreographer.doFrame(Choreographer.java:696)
11-20 10:49:55.578 E/AndroidRuntime(13679): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
11-20 10:49:55.578 E/AndroidRuntime(13679): 	at android.os.Handler.handleCallback(Handler.java:873)
11-20 10:49:55.578 E/AndroidRuntime(13679): 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-20 10:49:55.578 E/AndroidRuntime(13679): 	at android.os.Looper.loop(Looper.java:193)
11-20 10:49:55.578 E/AndroidRuntime(13679): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
11-20 10:49:55.578 E/AndroidRuntime(13679): 	at java.lang.reflect.Method.invoke(Native Method)
11-20 10:49:55.578 E/AndroidRuntime(13679): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
11-20 10:49:55.578 E/AndroidRuntime(13679): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
11-20 10:49:55.579 E/ACRA    (13679): ACRA caught a IllegalArgumentException for org.jellyfin.androidtv
11-20 10:49:55.579 E/ACRA    (13679): java.lang.IllegalArgumentException: Cannot format given Object as a Date
11-20 10:49:55.579 E/ACRA    (13679): 	at java.text.DateFormat.format(DateFormat.java:306)
11-20 10:49:55.579 E/ACRA    (13679): 	at java.text.Format.format(Format.java:157)
11-20 10:49:55.579 E/ACRA    (13679): 	at org.jellyfin.androidtv.util.apiclient.BaseItemUtils.getProgramSubText(BaseItemUtils.kt:145)
11-20 10:49:55.579 E/ACRA    (13679): 	at org.jellyfin.androidtv.ui.InfoRowView.addProgramInfo(InfoRowView.kt:238)
11-20 10:49:55.579 E/ACRA    (13679): 	at org.jellyfin.androidtv.ui.InfoRowView.buildDefaultInfoRow(InfoRowView.kt:155)
11-20 10:49:55.579 E/ACRA    (13679): 	at org.jellyfin.androidtv.ui.InfoRowView.updateView(InfoRowView.kt:129)
11-20 10:49:55.579 E/ACRA    (13679): 	at org.jellyfin.androidtv.ui.InfoRowView.access$updateView(InfoRowView.kt:43)
11-20 10:49:55.579 E/ACRA    (13679): 	at org.jellyfin.androidtv.ui.InfoRowView$setBaseItem$$inlined$doOnPreDraw$1.run(View.kt:433)
11-20 10:49:55.579 E/ACRA    (13679): 	at androidx.core.view.OneShotPreDrawListener.onPreDraw(OneShotPreDrawListener.java:71)
11-20 10:49:55.579 E/ACRA    (13679): 	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:977)
11-20 10:49:55.579 E/ACRA    (13679): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2476)
11-20 10:49:55.579 E/ACRA    (13679): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1462)
11-20 10:49:55.579 E/ACRA    (13679): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7185)
11-20 10:49:55.579 E/ACRA    (13679): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
11-20 10:49:55.579 E/ACRA    (13679): 	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
11-20 10:49:55.579 E/ACRA    (13679): 	at android.view.Choreographer.doFrame(Choreographer.java:696)
11-20 10:49:55.579 E/ACRA    (13679): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
11-20 10:49:55.579 E/ACRA    (13679): 	at android.os.Handler.handleCallback(Handler.java:873)
11-20 10:49:55.579 E/ACRA    (13679): 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-20 10:49:55.579 E/ACRA    (13679): 	at android.os.Looper.loop(Looper.java:193)
11-20 10:49:55.579 E/ACRA    (13679): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
11-20 10:49:55.579 E/ACRA    (13679): 	at java.lang.reflect.Method.invoke(Native Method)
11-20 10:49:55.579 E/ACRA    (13679): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
11-20 10:49:55.579 E/ACRA    (13679): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
11-20 10:49:55.579 D/ACRA    (13679): Building report
11-20 10:49:55.580 D/ACRA    (13679): Starting collectors with priority FIRST
11-20 10:49:55.581 D/ACRA    (13679): Calling collector org.acra.collector.DropBoxCollector
11-20 10:49:55.581 D/ACRA    (13679): Collector org.acra.collector.DropBoxCollector completed
11-20 10:49:55.582 D/ACRA    (13679): Calling collector org.acra.collector.LogCatCollector
11-20 10:49:55.582 D/ACRA    (13679): Calling collector org.acra.collector.StacktraceCollector
11-20 10:49:55.583 D/ACRA    (13679): Collector org.acra.collector.StacktraceCollector completed
11-20 10:49:55.584 D/ACRA    (13679): Retrieving logcat output (buffer:default)...

```  

### App information

***App version***: `0.14.9-zidoo_edition.beta11` (`140999`)  
***Package name***: `org.jellyfin.androidtv`  
***Build***: 
```json
{"BOARD":"mjolnir","BOOTLOADER":"unknown","BRAND":"rtk","CPU_ABI":"armeabi-v7a","CPU_ABI2":"armeabi","DEVICE":"thor32","DISPLAY":"thor32-userdebug 9 PPR1.180610.011 eng.jiangb.20220521.152934 test-keys","FINGERPRINT":"rtk\/thor32\/thor32:9\/PPR1.180610.011\/jiangbo05211528:userdebug\/test-keys","HARDWARE":"thor","HOST":"ZidooServer","ID":"PPR1.180610.011","IS_DEBUGGABLE":true,"IS_EMULATOR":false,"MANUFACTURER":"ZIDOO","MODEL":"Z9X","PERMISSIONS_REVIEW_REQUIRED":false,"PRODUCT":"thor32","RADIO":"unknown","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":[],"SUPPORTED_ABIS":["armeabi-v7a","armeabi"],"TAGS":"test-keys","TIME":1653118118000,"TYPE":"userdebug","UNKNOWN":"unknown","USER":"jiangbo","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"","CODENAME":"REL","FIRST_SDK_INT":28,"INCREMENTAL":"eng.jiangb.20220521.152934","PREVIEW_SDK_INT":0,"RELEASE":"9","RESOURCES_SDK_INT":28,"SDK":"28","SDK_INT":28,"SECURITY_PATCH":"2018-08-05"}}
```  
***Build config***: 
```json
{"APPLICATION_ID":"org.jellyfin.androidtv","BUILD_TYPE":"release","DEBUG":false,"DEVELOPMENT":false,"VERSION_CODE":140999,"VERSION_NAME":"0.14.9-zidoo_edition.beta11"}
```  

### Device information

***Android version***: `9`  
***Device brand***: `rtk`  
***Device product***: `thor32`  
***Device model***: `Z9X`  

### Crash information

***Start time***: `2022-11-20T10:49:50.311-07:00`  
***Crash time***: `2022-11-20T10:49:55.621-07:00`  

### Application version

0.14.9

### Device information

Zidoo Z9X

### Android version

Android 9

### Jellyfin server version

10.8.7

**Comment by doodlebro** [comment]
I believe this is fixed (and was caused) by the latest upstream android TV app, will test as soon as the Z9X port is updated.

**Comment by chminsc** [comment]
its caused of the date format issue. i fixed it
